spring:
  datasource:
#    url: jdbc:mariadb://test-db:3306/hoho # ${DB_URL}  or jdbc:mysql://localhost:3306/hoandlee
    url: jdbc:mariadb://localhost:3306/hoho
    username: root #${DB_USER} # ex) root
    password: 1234 #${DB_PASSWORD} # ex) 1234

#    url: jdbc:mariadb://10.168.174.244:3306/maria
#    username : root
#    password : root

#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver

  mvc:
#    view:      # ViewResolver 설정 추가
#      prefix: /
#      suffix: .html
    throw-exception-if-no-handler-found: true  # 예외 처리 설정 추가

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
  thymeleaf:
    cache: false

  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
    org.springframework.security: DEBUG

server:
  error:
    whitelabel:
      enabled: false
  port: 8080
  servlet:
    context-path: /
#  공백('')으로 표시되는 이유는 context-path를 루트(/)로 설정.
#  루트(/)는 웹 어플리케이션의 최상위 경로

jwt:
  secret: NH1CN4FB3N2buaV1zZUPvJ6mkvp+Xj3mazMDEm5ofoA= #${JWT_TOKEN} # 환경변수에서 JWT 시크릿 키를 가져옴
  expireTime: 604800 #${JWT_EXPIRE_TIME} # 환경변수에서 JWT 만료 시간을 가져옴
